version: "3.8"

services:
  api:
    image: jhumanj/opnform-api:latest
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      DB_DATABASE: ${DB_DATABASE:-forge}
      DB_USERNAME: ${DB_USERNAME:-forge}
      DB_PASSWORD: ${DB_PASSWORD:-forge}
      DB_CONNECTION: ${DB_CONNECTION:-pgsql}
      FILESYSTEM_DISK: local
      LOCAL_FILESYSTEM_VISIBILITY: public
    env_file:
      - ./api/.env
    volumes:
      - opnform_storage:/usr/share/nginx/html/storage:rw
    depends_on:
      - db
      - redis
    networks:
      - dokploy-network

  api-worker:
    image: jhumanj/opnform-api:latest
    command: php artisan queue:work
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      DB_DATABASE: ${DB_DATABASE:-forge}
      DB_USERNAME: ${DB_USERNAME:-forge}
      DB_PASSWORD: ${DB_PASSWORD:-forge}
      DB_CONNECTION: ${DB_CONNECTION:-pgsql}
      FILESYSTEM_DISK: local
      LOCAL_FILESYSTEM_VISIBILITY: public
      IS_API_WORKER: "true"
    env_file:
      - ./api/.env
    volumes:
      - opnform_storage:/usr/share/nginx/html/storage:rw
    depends_on:
      - db
      - redis
    networks:
      - dokploy-network

  ui:
    image: jhumanj/opnform-client:latest
    environment:
      NUXT_PUBLIC_APP_URL:/
      NUXT_PUBLIC_API_BASE:/api
      NUXT_PRIVATE_API_BASE:http://opnform-project-form-zgxxfr/api
      NUXT_PUBLIC_ENV:dev
      NUXT_API_SECRET:2q7WZRFL2ppZjKV7u8PdD8btIyy0TVdQD8EWflCa

    networks:
      - dokploy-network

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - dokploy-network

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_DATABASE:-forge}
      POSTGRES_USER: ${DB_USERNAME:-forge}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-forge}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-forge}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dokploy-network

volumes:
  postgres-data:
  opnform_storage:

networks:
  dokploy-network:
    external: true
